11 get reviews queries
hlilya/be-final-project pull request #11
Opened 2022-11-16 11:53 UTC by hlilya

2022-11-16 13:09 UTC, dav3rid requested changes

2022-11-16 13:09 UTC, dav3rid commented on __tests__/app.test.js
> +        expect(reviews).toBeSortedBy("created_at", { descending: true });
It seems a little odd to assert a sort order on an array you've asserted only has a single element in - can remove if you'd like

2022-11-16 13:09 UTC, dav3rid commented on __tests__/app.test.js
> +              category: expect.any(String),
This property does want to be specific here - nothing about this assertion proves reviews from the correct category are present

2022-11-16 13:09 UTC, dav3rid commented on __tests__/app.test.js
> +  });
Makes sense to have changed the category - still need to assert the category property though

2022-11-16 13:09 UTC, dav3rid commented on __tests__/app.test.js
> +        reviews.forEach((reviews) => {
No real need to assert the structure of each object in the array here - you've already done that in previous tests - just the sort order and direction would be sufficient

2022-11-16 13:09 UTC, dav3rid commented on __tests__/app.test.js
> +  });
error tests look good but need some more - same problems but for order
Another consideration - what if a category exists but has no reviews associated?

2022-11-16 13:09 UTC, dav3rid commented on db/models/models.js
> +    queryStr += `WHERE reviews.category = '${category}'`;
You're open to sql injection here! MUST use parameterised query $ syntax instead

2022-11-16 13:09 UTC, dav3rid commented on db/models/models.js
> + ORDER BY ${sort_by} ${order};`;
Also here - order will need to be manually sanitised above just like sort_by

2022-11-16 13:09 UTC, dav3rid commented on db/models/models.js
> +    if (reviews.length === 0) {
This is where you could ensure exactly why the array is empty

2022-11-17 10:27 UTC, MKD01 approved these changes
Happy for this to be merged after these changes have been made

2022-11-17 10:27 UTC, MKD01 commented on __tests__/app.test.js
> +      expect(reviews).toBeInstanceOf(Array);
The assertion of this being an array does not ned to be made as you have a forEach which is an array method itself, so would make that check for you.

2022-11-17 10:38 UTC, merged